name: Build Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      matrix:
        # 🛑 FIX: Define the actual keyboard folder names within your user directory
        keyboard_folder:
          - <YOUR_KEYBOARD_FOLDER_NAME> # Example: 'lily58' or 'gmmk'
          # You can add more keyboard folders here if you have them

    steps:
      - name: Checkout QMK Firmware
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          submodules: recursive

      - name: Checkout userspace (Your Repo)
        uses: actions/checkout@v4
        with:
          # This correctly places your repo content into qmk_firmware/users/Umang5848/
          path: users/${{ github.actor }} 

      - name: Build firmware with VIAL
        # ✅ FIX APPLIED: Combines the username and the keyboard folder name
        # Correct format: -kb [user_name]/[keyboard_name]
        run: qmk compile -kb ${{ github.actor }}/${{ matrix.keyboard_folder }} -km vial

      - name: Archive firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.keyboard_folder }}-${{ github.actor }}
          path: |
            *.uf2
            *.bin
            *.hex
          if-no-files-found: error
